server:
  port: 8083

spring:
  data:
    mongodb:
      uri: 
      database: Traceability
  security:
    user:
      name: root
      password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: DnkM6Yeq/oVtI4WHmTHqCUSpFZ4eNvPqI7xnsq1upr4=
      expiration: 86400000
      refresh-token:
        expiration: 604800000

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
